version: "3.0"
services:

  postgres_spring:
    container_name: postgres_spring
    image: postgres:alpine
    restart: always
    ports:
      - 5557:5432
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: spring_user
      POSTGRES_PASSWORD: spring_pass
    volumes:
      - db_data_spring:/var/lib/postgresql/data:rw

volumes:
  db_data_spring:
