
spring:
        application:
                name: spring-test

        datasource:
                url: jdbc:postgresql://localhost:5557/spring
                username: spring_user
                password: spring_pass
                driverClassName: org.postgresql.Driver
        h2:
                console.enabled: true
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true
                properties:
                        hibernate:
                                dialect: org.hibernate.dialect.PostgreSQLDialect
                                format_sql: false
                                show_sql: false



#        jpa:
#                hibernate:
#                        ddl-auto: update
#                show-sql: true
#                properties:
#                        hibernate:
#                                format_sql: false
#                                show_sql: false


#logging:
#        config: logback-dev.xml